### PR TITLE
ISSUE-61: Make VBO Facet aware! (I DID IT!)

### PR DESCRIPTION
**Pull request by DiegoPino**
# What?

See #61 

Took me so many hours of debugging but this code is GOLD! VBO (ViewsBulkOperations) now is totally able to work with Facets, which means search/replace/export to CSV just became MUCH more fun.  Because this is based on my other open issues you might see more commits, but once #94 is in, this will merge clean.

To make this happen you need to update your code, then go the Facets for a Views (Facet source) that has VBO (the default one  is `Search and replace` views with `page_1` display and set e.g this

image

There is an issue with Facets that processors (NOT ON ME) that do not have a config won't be processed. Who would have guessed that! (so save it to generated a config)

SUPER FUN!

### CODE REVIEW

**Comment by patdunlavey** [comment]
Hi Diego. It looks like this merge needs a symfony http-foundation update that I do not have in order to work. Is that composer requirement provided in another archi package?

On [line 171 of src/Plugin/facets/processor/VboBatchProcessorHandler.php](https://github.com/esmero/ami/blob/0.4.0/src/Plugin/facets/processor/VboBatchProcessorHandler.php#L171), it calls `\Symfony\Component\HttpFoundation\RequestStack::getMainRequest`. That method first appears (under that name) in the 6.1.2 version [here](https://github.com/symfony/http-foundation/commit/75446ebe3694a4ec8b8c541121ab8515bbfe07e9). 

Currently, I have 4.4.25 as the http-foundation version:
```
bash-5.1# composer show symfony/http-foundation | grep 'versions :'
versions : * v4.4.25
```
This is who is requiring it:
```
bash-5.1# composer depends symfony/http-foundation
asm89/stack-cors                 1.3.0    requires  symfony/http-foundation (~2.7|~3.0|~4.0|~5.0)  
drupal/core                      9.2.21   requires  symfony/http-foundation (^4.4.7)               
drupal/core-recommended          9.2.21   requires  symfony/http-foundation (v4.4.25)              
stack/builder                    v1.0.6   requires  symfony/http-foundation (~2.1|~3.0|~4.0|~5.0)  
symfony/http-kernel              v4.4.25  requires  symfony/http-foundation (^4.4|^5.0)            
symfony/psr-http-message-bridge  v2.1.0   requires  symfony/http-foundation (^4.4 || ^5.0)         
```

**Comment by DiegoPino** [comment]
@patdunlavey probably related to you being on Drupal 9.2?

I should make this one still Drupal 9.2 aware... mmmm??

https://www.drupal.org/node/3253744

See, Drupal is already adding the compatibility layer. But on an older Drupal it won't work. Can you check your drupal? If not I can add the Alternative in the constructor to allow this to work well on Drupal 8.9 and <= 9.2

<?php

namespace Drupal\Core\Http;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack as SymfonyRequestStack;

/**
 * Forward-compatibility shim for Symfony's RequestStack.
 *
 * @todo https://www.drupal.org/node/3265121 Remove in Drupal 10.0.x.
 */
class RequestStack extends SymfonyRequestStack {

  /**
   * Gets the main request.
   *
   * @return \Symfony\Component\HttpFoundation\Request|null
   *   The main request.
   */
  public function getMainRequest(): ?Request {
    if (method_exists(SymfonyRequestStack::class, 'getMainRequest')) {
      return parent::getMainRequest();
    }
    else {
      return parent::getMasterRequest();
    }
  }

  /**
   * {@inheritdoc}
   */
  public function getMasterRequest() {
    @trigger_error(__METHOD__ . '() is deprecated in drupal:9.3.0 and is removed from drupal:10.0.0. Use getMainRequest() instead. See https://www.drupal.org/node/3253744', E_USER_DEPRECATED);
    return $this->getMainRequest();
  }

**Comment by patdunlavey** [comment]
It seems fine to me to make drupal/core : ^9.3 a requirement. I just don't see that yet in [ami's composer.json](https://github.com/esmero/ami/blob/0.4.0/composer.json) or in [archipelago-deployment](https://github.com/esmero/archipelago-deployment/blob/1.0.0/composer.json) or [archipelago-deployment-live](https://github.com/esmero/archipelago-deployment-live/blob/1.0.0/drupal/composer.default.json). Would it make sense to just make a PR for ami with that change to composer.json, since it's the only archipelago module that currently needs ^9.3? In theory, one could install and run archipelago without ami, so targeting the bumped drupal version requirement to just ami might make sense?
Thanks!

**Comment by DiegoPino** [comment]
@patdunlavey release is on prep this week (have not announced and the branch is not closed). So will make sure I get this right. thanks!

**Pull request merged**
